[versions]
jvmTarget = "1.8"
agp = "8.3.1"
kotlin = "1.9.22"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
junit = "4.13.2"
mockk = "1.13.9"
mockk-common = "1.12.5"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-common = { group = "io.mockk", name = "mockk-common", version.ref = "mockk-common" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
